from app.db.session import SessionLocal
from app.repositories.supplier_repository import SupplierRepository
from app.schemas.supplier import SupplierCreate
from app.services import vector_store
from app.services.embedding_service import embed_passage, embed_passages
from app.services.supplier_service import supplier_embedding_chunks, supplier_embedding_text

# Демонстрационные данные: вымышленные компании, показывают состав полей и
# структуру карточки (status=demo).
DEMO_SUPPLIERS: list[dict] = [
    # мясо и птица
    {
        "name": "Уральские фермы (демо)",
        "category": "мясо и птица",
        "region": "Екатеринбург",
        "description": "Мясо и птица от локальных ферм, поставки 2 раза в неделю.",
        "product_lines": "говядина, свинина, курица",
        "moq": "от 20 кг",
        "price_note": "от 420 ₽/кг, зависит от отруба",
        "certificates": "ХАССП, ветеринарные свидетельства",
        "delivery_terms": "своя машина, доставка 1-2 дня",
        "notes": "демонстрационная запись, не настоящая компания",
    },
    {
        "name": "МясТорг Сибирь (демо)",
        "category": "мясо и птица",
        "region": "Новосибирск",
        "description": "Оптовые поставки охлаждённого мяса для ресторанов и кейтеринга.",
        "product_lines": "говядина, баранина, субпродукты",
        "moq": "от 25 кг",
        "price_note": "от 480 ₽/кг",
        "certificates": "ветеринарные свидетельства",
        "delivery_terms": "рефрижератор, 1-2 дня по городу",
        "notes": "демонстрационная запись, не настоящая компания",
    },
    {
        "name": "Куриный Двор (демо)",
        "category": "мясо и птица",
        "region": "Краснодар",
        "description": "Птицефабрика, прямые поставки куриного мяса и полуфабрикатов.",
        "product_lines": "курица целиком, филе, крылья",
        "moq": "от 30 кг",
        "price_note": None,
        "certificates": "декларация соответствия",
        "delivery_terms": "по ЮФО, 1-3 дня",
        "notes": "демонстрационная запись, не настоящая компания",
    },
    {
        "name": "Фермерская Говядина (демо)",
        "category": "мясо и птица",
        "region": "Казань",
        "description": "Мраморная говядина от фермерских хозяйств Татарстана.",
        "product_lines": "мраморная говядина, стейки",
        "moq": None,
        "price_note": "от 890 ₽/кг",
        "certificates": None,
        "delivery_terms": "рефрижератор по ПФО",
        "notes": "демонстрационная запись, не настоящая компания",
    },
    # молочная продукция
    {
        "name": "Молочный дом (демо)",
        "category": "молочная продукция",
        "region": "Казань",
        "description": "Молочная продукция для HoReCa: сыры, сливки, масло.",
        "product_lines": "сыры, сливки, масло",
        "moq": "от 10 кг по позиции",
        "price_note": None,
        "certificates": "декларация соответствия ЕАЭС",
        "delivery_terms": "рефрижератор, 1 день по городу",
        "notes": "демонстрационная запись, не настоящая компания",
    },
    {
        "name": "СырОпт Урал (демо)",
        "category": "молочная продукция",
        "region": "Екатеринбург",
        "description": "Твёрдые и полутвёрдые сыры собственного производства.",
        "product_lines": "сыр гауда, чеддер, сулугуни",
        "moq": "от 15 кг",
        "price_note": "от 620 ₽/кг",
        "certificates": "ХАССП",
        "delivery_terms": "по Уралу, 1-2 дня",
        "notes": "демонстрационная запись, не настоящая компания",
    },
    {
        "name": "Творожный Край (демо)",
        "category": "молочная продукция",
        "region": "Пермь",
        "description": "Творог, сметана и йогурты для кафе и пекарен.",
        "product_lines": "творог, сметана, йогурт",
        "moq": "от 10 кг",
        "price_note": None,
        "certificates": None,
        "delivery_terms": "рефрижератор, 1 день",
        "notes": "демонстрационная запись, не настоящая компания",
    },
    {
        "name": "Молоко и Ко (демо)",
        "category": "молочная продукция",
        "region": "Москва",
        "description": "Пастеризованное молоко и сливки оптом для кофеен и пекарен.",
        "product_lines": "молоко, сливки для взбивания",
        "moq": "от 50 л",
        "price_note": "от 95 ₽/л",
        "certificates": "декларация соответствия",
        "delivery_terms": "по Москве и МО ежедневно",
        "notes": "демонстрационная запись, не настоящая компания",
    },
    # рыба и морепродукты
    {
        "name": "Морепродукт Опт (демо)",
        "category": "рыба и морепродукты",
        "region": "Владивосток",
        "description": "Рыба и морепродукты, прямые поставки с побережья.",
        "product_lines": "рыба, морепродукты",
        "moq": "от 30 кг",
        "price_note": None,
        "certificates": "ветеринарные документы, ХАССП",
        "delivery_terms": "авиадоставка в регионы, 2-4 дня",
        "notes": "демонстрационная запись, не настоящая компания",
    },
    {
        "name": "Балтийский Улов (демо)",
        "category": "рыба и морепродукты",
        "region": "Санкт-Петербург",
        "description": "Охлаждённая и мороженая рыба балтийского вылова.",
        "product_lines": "лосось, треска, сельдь",
        "moq": "от 20 кг",
        "price_note": "от 540 ₽/кг",
        "certificates": "ветеринарные документы",
        "delivery_terms": "по СЗФО, 1-2 дня",
        "notes": "демонстрационная запись, не настоящая компания",
    },
    {
        "name": "КреветкаОпт (демо)",
        "category": "рыба и морепродукты",
        "region": "Москва",
        "description": "Замороженные креветки и морской коктейль для ресторанов.",
        "product_lines": "креветки, морской коктейль, кальмары",
        "moq": None,
        "price_note": "от 780 ₽/кг",
        "certificates": None,
        "delivery_terms": "по Москве и МО",
        "notes": "демонстрационная запись, не настоящая компания",
    },
    {
        "name": "Дальневосточная Рыба (демо)",
        "category": "рыба и морепродукты",
        "region": "Хабаровск",
        "description": "Красная рыба и икра прямо с промысла.",
        "product_lines": "горбуша, кета, икра",
        "moq": "от 10 кг",
        "price_note": None,
        "certificates": "ветеринарные документы",
        "delivery_terms": "по путине, авиадоставка в регионы",
        "notes": "демонстрационная запись, не настоящая компания",
    },
    # овощи и фрукты
    {
        "name": "ГрузОвощ (демо)",
        "category": "овощи и фрукты",
        "region": "Москва",
        "description": "Оптовые поставки овощей и зелени с ежедневной свежестью.",
        "product_lines": "овощи, зелень",
        "moq": "от 15 кг",
        "price_note": "сезонные цены, обновление раз в день",
        "certificates": "фитосанитарные сертификаты",
        "delivery_terms": "ежедневно, заказ до 18:00 на завтра",
        "notes": "демонстрационная запись, не настоящая компания",
    },
    {
        "name": "ФрешЯгода (демо)",
        "category": "овощи и фрукты",
        "region": "Краснодар",
        "description": "Свежие и замороженные ягоды для десертов и напитков.",
        "product_lines": "ягоды свежие и замороженные",
        "moq": "от 10 кг",
        "price_note": "сезонные цены",
        "certificates": "фитосанитарный сертификат",
        "delivery_terms": "рефрижератор, 2-3 дня по РФ",
        "notes": "демонстрационная запись, не настоящая компания",
    },
    {
        "name": "Фруктовая База (демо)",
        "category": "овощи и фрукты",
        "region": "Екатеринбург",
        "description": "Импортные и отечественные фрукты оптом для ресторанов.",
        "product_lines": "цитрусовые, яблоки, бананы",
        "moq": "от 20 кг",
        "price_note": None,
        "certificates": None,
        "delivery_terms": "по Уралу, 1-2 дня",
        "notes": "демонстрационная запись, не настоящая компания",
    },
    {
        "name": "ОвощТрейд (демо)",
        "category": "овощи и фрукты",
        "region": "Ростов-на-Дону",
        "description": "Корнеплоды и овощи борщевого набора оптом.",
        "product_lines": "картофель, морковь, свёкла, лук",
        "moq": "от 50 кг",
        "price_note": "от 25 ₽/кг",
        "certificates": "фитосанитарный сертификат",
        "delivery_terms": "по ЮФО, 1-2 дня",
        "notes": "демонстрационная запись, не настоящая компания",
    },
    # специи и соусы
    {
        "name": "СпецПряность (демо)",
        "category": "специи и соусы",
        "region": "Москва",
        "description": "Специи, соусы и приправы для азиатской и восточной кухни.",
        "product_lines": "специи, соусы, приправы",
        "moq": "от 5 кг по позиции",
        "price_note": "от 300 ₽/кг",
        "certificates": "декларация соответствия ЕАЭС",
        "delivery_terms": "доставка транспортной компанией, 3-5 дней",
        "notes": "демонстрационная запись, не настоящая компания",
    },
    {
        "name": "СоусМастер (демо)",
        "category": "специи и соусы",
        "region": "Санкт-Петербург",
        "description": "Соусы и заправки собственного производства для HoReCa.",
        "product_lines": "кетчуп, майонез, соусы для пасты",
        "moq": "от 10 кг",
        "price_note": None,
        "certificates": "ХАССП",
        "delivery_terms": "по СЗФО, 2-3 дня",
        "notes": "демонстрационная запись, не настоящая компания",
    },
    {
        "name": "Восточный Базар (демо)",
        "category": "специи и соусы",
        "region": "Казань",
        "description": "Специи и травы, закупка напрямую у производителей.",
        "product_lines": "куркума, зира, паприка, смеси специй",
        "moq": "от 3 кг по позиции",
        "price_note": "от 450 ₽/кг",
        "certificates": None,
        "delivery_terms": "по ПФО, 2-4 дня",
        "notes": "демонстрационная запись, не настоящая компания",
    },
    {
        "name": "СольПерец Опт (демо)",
        "category": "специи и соусы",
        "region": "Новосибирск",
        "description": "Базовые специи крупным оптом для сетевых заведений.",
        "product_lines": "соль, перец, лавровый лист",
        "moq": "от 20 кг",
        "price_note": None,
        "certificates": None,
        "delivery_terms": None,
        "notes": "демонстрационная запись, не настоящая компания",
    },
    # напитки
    {
        "name": "КрафтНапиток (демо)",
        "category": "напитки",
        "region": "Москва",
        "description": "Лимонады и морсы на заказ, можно под собственную этикетку.",
        "product_lines": "лимонады, морсы",
        "moq": "от 200 л",
        "price_note": "от 90 ₽/л",
        "certificates": "декларация соответствия",
        "delivery_terms": "по Москве и МО, 3-5 дней на производство",
        "notes": "демонстрационная запись, не настоящая компания",
    },
    {
        "name": "КофеОпт (демо)",
        "category": "напитки",
        "region": "Санкт-Петербург",
        "description": "Кофе в зёрнах и молотый для кофеен и ресторанов.",
        "product_lines": "кофе в зёрнах, молотый кофе",
        "moq": "от 10 кг",
        "price_note": "от 1100 ₽/кг",
        "certificates": None,
        "delivery_terms": "по СЗФО, 1-2 дня",
        "notes": "демонстрационная запись, не настоящая компания",
    },
    {
        "name": "ЧайДом (демо)",
        "category": "напитки",
        "region": "Екатеринбург",
        "description": "Листовой и пакетированный чай для HoReCa.",
        "product_lines": "чёрный чай, зелёный чай, травяные сборы",
        "moq": "от 5 кг",
        "price_note": None,
        "certificates": None,
        "delivery_terms": "по Уралу, 2-3 дня",
        "notes": "демонстрационная запись, не настоящая компания",
    },
    {
        "name": "СокЗавод (демо)",
        "category": "напитки",
        "region": "Краснодар",
        "description": "Натуральные соки прямого отжима оптом.",
        "product_lines": "апельсиновый сок, яблочный сок",
        "moq": "от 100 л",
        "price_note": "от 140 ₽/л",
        "certificates": "декларация соответствия",
        "delivery_terms": "по ЮФО, 2-3 дня",
        "notes": "демонстрационная запись, не настоящая компания",
    },
    # выпечка и готовая продукция
    {
        "name": "PastaLab (демо)",
        "category": "выпечка и готовая продукция",
        "region": "Санкт-Петербург",
        "description": "Полуфабрикаты и соусы для пасты собственного производства.",
        "product_lines": "паста, соусы",
        "moq": "от 10 кг по SKU",
        "price_note": "от 280 ₽/кг",
        "certificates": "ХАССП",
        "delivery_terms": "заморозка, доставка по СЗФО 1-3 дня",
        "notes": "демонстрационная запись, не настоящая компания",
    },
    {
        "name": "БулкаХлеб (демо)",
        "category": "выпечка и готовая продукция",
        "region": "Екатеринбург",
        "description": "Булочки для бургеров и хлеб на заказ, ежедневная выпечка.",
        "product_lines": "булочки для бургеров, хлеб",
        "moq": "от 100 шт по позиции",
        "price_note": "от 22 ₽/шт",
        "certificates": "декларация соответствия",
        "delivery_terms": "ежедневно с утра по городу",
        "notes": "демонстрационная запись, не настоящая компания",
    },
    {
        "name": "Пекарня Онлайн (демо)",
        "category": "выпечка и готовая продукция",
        "region": "Москва",
        "description": "Слоёная выпечка и десерты для кафе и кофеен.",
        "product_lines": "круассаны, эклеры, чизкейки",
        "moq": "от 50 шт",
        "price_note": None,
        "certificates": None,
        "delivery_terms": "по Москве, ежедневно",
        "notes": "демонстрационная запись, не настоящая компания",
    },
    {
        "name": "ПельмениОпт (демо)",
        "category": "выпечка и готовая продукция",
        "region": "Новосибирск",
        "description": "Замороженные полуфабрикаты: пельмени, вареники, блины.",
        "product_lines": "пельмени, вареники, блины",
        "moq": "от 30 кг",
        "price_note": "от 320 ₽/кг",
        "certificates": "ХАССП",
        "delivery_terms": "заморозка, по Сибири 2-4 дня",
        "notes": "демонстрационная запись, не настоящая компания",
    },
    {
        "name": "СушиЛаб (демо)",
        "category": "выпечка и готовая продукция",
        "region": "Санкт-Петербург",
        "description": "Полуфабрикаты для суши и роллов: рис, нори, соусы.",
        "product_lines": "рис для суши, нори, соус унаги",
        "moq": None,
        "price_note": None,
        "certificates": None,
        "delivery_terms": "по СЗФО, 2-3 дня",
        "notes": "демонстрационная запись, не настоящая компания",
    },
    # упаковка
    {
        "name": "СибПак (демо)",
        "category": "упаковка",
        "region": "Новосибирск",
        "description": "Экологичная упаковка для доставки еды: боксы, крышки, приборы.",
        "product_lines": "боксы, крышки, приборы",
        "moq": "от 5000 шт",
        "price_note": "от 6 ₽/шт",
        "certificates": "сертификат на контакт с пищевыми продуктами",
        "delivery_terms": "доставка транспортной компанией, 3-7 дней",
        "notes": "демонстрационная запись, не настоящая компания",
    },
    {
        "name": "ЭкоКоробка (демо)",
        "category": "упаковка",
        "region": "Екатеринбург",
        "description": "Крафтовая упаковка и пакеты с логотипом на заказ.",
        "product_lines": "коробки, пакеты с нанесением",
        "moq": "от 1000 шт с нанесением",
        "price_note": "от 8 ₽/шт",
        "certificates": None,
        "delivery_terms": "самовывоз или ТК, 5-10 дней с печатью",
        "notes": "демонстрационная запись, не настоящая компания",
    },
    {
        "name": "УпакСервис (демо)",
        "category": "упаковка",
        "region": "Санкт-Петербург",
        "description": "Термопакеты и контейнеры для сохранения температуры при доставке.",
        "product_lines": "термопакеты, термоконтейнеры",
        "moq": "от 500 шт",
        "price_note": "от 45 ₽/шт",
        "certificates": None,
        "delivery_terms": "по СЗФО 2-4 дня, по РФ дольше",
        "notes": "демонстрационная запись, не настоящая компания",
    },
    {
        "name": "ПакетПром (демо)",
        "category": "упаковка",
        "region": "Москва",
        "description": "Бумажные пакеты и стаканы для кофеен и фастфуда.",
        "product_lines": "бумажные пакеты, стаканы, крафт-подложки",
        "moq": "от 2000 шт",
        "price_note": None,
        "certificates": None,
        "delivery_terms": "по Москве и МО, 3-5 дней",
        "notes": "демонстрационная запись, не настоящая компания",
    },
    {
        "name": "ЛентаУпак (демо)",
        "category": "упаковка",
        "region": "Казань",
        "description": "Плёнка, стретч и скотч для упаковки готовых блюд.",
        "product_lines": "пищевая плёнка, стретч-плёнка",
        "moq": "от 1000 шт",
        "price_note": "от 12 ₽/шт",
        "certificates": "сертификат на контакт с пищевыми продуктами",
        "delivery_terms": "по ПФО, 2-3 дня",
        "notes": "демонстрационная запись, не настоящая компания",
    },
    # оборудование и инвентарь
    {
        "name": "ТехноХолод (демо)",
        "category": "оборудование и инвентарь",
        "region": "Екатеринбург",
        "description": "Аренда и обслуживание холодильного оборудования для кухонь.",
        "product_lines": "холодильные камеры, морозильные лари",
        "moq": None,
        "price_note": "от 3500 ₽/мес за единицу оборудования",
        "certificates": None,
        "delivery_terms": "монтаж и сервис по Уралу",
        "notes": "демонстрационная запись, не настоящая компания",
    },
    {
        "name": "КухняПро (демо)",
        "category": "оборудование и инвентарь",
        "region": "Москва",
        "description": "Профессиональное кухонное оборудование для ресторанов.",
        "product_lines": "плиты, пароконвектоматы, миксеры",
        "moq": None,
        "price_note": None,
        "certificates": "сертификат соответствия ТР ТС",
        "delivery_terms": "по Москве и МО, монтаж включён",
        "notes": "демонстрационная запись, не настоящая компания",
    },
    {
        "name": "ИнвентарьОпт (демо)",
        "category": "оборудование и инвентарь",
        "region": "Санкт-Петербург",
        "description": "Посуда и инвентарь для кухни: ножи, разделочные доски, формы.",
        "product_lines": "ножи, разделочные доски, формы для выпечки",
        "moq": "от 20 шт по позиции",
        "price_note": "от 350 ₽/шт",
        "certificates": None,
        "delivery_terms": "по СЗФО, 2-4 дня",
        "notes": "демонстрационная запись, не настоящая компания",
    },
    {
        "name": "БарТех (демо)",
        "category": "оборудование и инвентарь",
        "region": "Краснодар",
        "description": "Оборудование для баров: кофемашины, блендеры, ледогенераторы.",
        "product_lines": "кофемашины, блендеры, ледогенераторы",
        "moq": None,
        "price_note": None,
        "certificates": None,
        "delivery_terms": "по ЮФО, монтаж и обучение персонала",
        "notes": "демонстрационная запись, не настоящая компания",
    },
    # логистика и доставка
    {
        "name": "ДоставкаПлюс Логистика (демо)",
        "category": "логистика и доставка",
        "region": "Москва",
        "description": "Аутсорс курьерской доставки для ресторанов и дарксторов.",
        "product_lines": None,
        "moq": None,
        "price_note": "от 99 ₽/заказ, зависит от зоны",
        "certificates": None,
        "delivery_terms": "запуск за 5-7 дней",
        "notes": "демонстрационная запись, не настоящая компания",
    },
    {
        "name": "ТермоВоз (демо)",
        "category": "логистика и доставка",
        "region": "Екатеринбург",
        "description": "Перевозка охлаждённых и замороженных продуктов рефрижераторами.",
        "product_lines": None,
        "moq": None,
        "price_note": "от 25 ₽/км",
        "certificates": None,
        "delivery_terms": "по Уралу и соседним регионам",
        "notes": "демонстрационная запись, не настоящая компания",
    },
    {
        "name": "СкладХаб (демо)",
        "category": "логистика и доставка",
        "region": "Санкт-Петербург",
        "description": "Ответственное хранение и фулфилмент для продуктового опта.",
        "product_lines": None,
        "moq": None,
        "price_note": None,
        "certificates": None,
        "delivery_terms": "склад с температурными зонами, отгрузка day-in-day-out",
        "notes": "демонстрационная запись, не настоящая компания",
    },
    {
        "name": "КурьерОпт (демо)",
        "category": "логистика и доставка",
        "region": "Новосибирск",
        "description": "Курьерская сеть для доставки продуктов заведениям по подписке.",
        "product_lines": None,
        "moq": None,
        "price_note": "от 150 ₽/заказ",
        "certificates": None,
        "delivery_terms": "по Новосибирску, ежедневно",
        "notes": "демонстрационная запись, не настоящая компания",
    },
]

# Настоящие компании, собранные через собственный веб-поиск сервиса
# (DuckDuckGo + разбор страницы моделью) по запросам "моцарелла для пиццерии",
# "упаковка для доставки еды", "молочная продукция для HoReCa" в Екатеринбурге.
# status=found — как и любая карточка из веб-поиска: источник и факты реальные,
# но человек их ещё не проверял.
REAL_SUPPLIERS: list[dict] = [
    {
        "name": "Mozaretti",
        "category": "молочная продукция",
        "region": "не указан",
        "description": "Производитель сыров для пиццы Mozaretti предлагает ассортимент сыров Моцарелла, идеально подходящих для сегмента HoReCa.",
        "product_lines": "моцарелла, сыры для пиццы",
        "moq": None,
        "price_note": None,
        "certificates": None,
        "delivery_terms": "доставка во все регионы",
        "notes": None,
        "source_url": "https://mozaretti.ru/",
    },
    {
        "name": "Fratelli Spirini",
        "category": "молочная продукция",
        "region": "Екатеринбург",
        "description": "Производство сыров, специализирующееся на моцарелле в рассоле.",
        "product_lines": "моцарелла в рассоле",
        "moq": None,
        "price_note": "210 ₽ за 140 г",
        "certificates": None,
        "delivery_terms": None,
        "notes": None,
        "source_url": "https://fratelli-spirini.ru/store/myagkie_svezhie_syry/mozzarella/",
    },
    {
        "name": "Milco Group",
        "category": "молочная продукция",
        "region": "Екатеринбург",
        "description": "Оптовая продажа сыров, произведённых по стандартам ГОСТ, для бизнеса.",
        "product_lines": "сыры",
        "moq": "от 600 кг",
        "price_note": None,
        "certificates": None,
        "delivery_terms": "доставка по Екатеринбургу и всей России",
        "notes": None,
        "source_url": "https://milco.group/syr-optom-ekaterinburg",
    },
    {
        "name": "УпакМосТорг",
        "category": "упаковка",
        "region": "Екатеринбург",
        "description": "Упаковочные материалы: коробки, конверты, пакеты на заказ и в наличии.",
        "product_lines": "коробки, конверты, пакеты",
        "moq": None,
        "price_note": None,
        "certificates": None,
        "delivery_terms": None,
        "notes": None,
        "source_url": "https://ekb.upakmostorg.ru/",
    },
    {
        "name": "Центр Упаковки",
        "category": "упаковка",
        "region": "Екатеринбург",
        "description": "Производство и продажа полиэтиленовой упаковки для пищевых продуктов.",
        "product_lines": "полиэтиленовая упаковка для пищевых продуктов",
        "moq": None,
        "price_note": None,
        "certificates": None,
        "delivery_terms": "доставка в Екатеринбурге, по области и всей России",
        "notes": None,
        "source_url": "https://center-upakovki.ru/catalog/upakovka-dlya-pishchevykh-produktov/",
    },
    {
        "name": "ЕКАПАК",
        "category": "упаковка",
        "region": "Екатеринбург",
        "description": "Производитель и поставщик гибкой пластиковой (вакуумной) упаковки для производственных и торговых предприятий.",
        "product_lines": "вакуумная упаковка",
        "moq": "от 50 000 ₽",
        "price_note": "от 1.06 ₽/шт",
        "certificates": None,
        "delivery_terms": "по Екатеринбургу бесплатно от 50 000 ₽, по России транспортной компанией до терминала",
        "notes": "собственное производство",
        "source_url": "https://ekapak.ru/",
    },
    {
        "name": "МИЛКОМ",
        "category": "молочная продукция",
        "region": "не указан",
        "description": "Поставщик молочной продукции для HoReCa: молоко, сыр, сливки, творог, сметана.",
        "product_lines": "молоко, сыр, сливки, творог, сметана",
        "moq": None,
        "price_note": None,
        "certificates": None,
        "delivery_terms": None,
        "notes": None,
        "source_url": "https://www.milkom-komos.ru/products/horeca/",
    },
    {
        "name": "ООО «ГРАНДПРОДУКТЕКБ»",
        "category": "овощи и фрукты",
        "region": "Екатеринбург",
        "description": "Оптовый поставщик продуктов питания для ресторанов, столовых, пекарен и кейтеринга.",
        "product_lines": None,
        "moq": None,
        "price_note": None,
        "certificates": "Честный Знак",
        "delivery_terms": "доставка по УРФО и Свердловской области бесплатно от 10 000 ₽, возможна в ХМАО и ЯНАО",
        "notes": "скидки при больших закупках",
        "source_url": "https://grandproduktekb.ru/",
    },
    {
        "name": "ООО «Наш Союз»",
        "category": "мясо и птица",
        "region": "Екатеринбург",
        "description": "Оптовый дистрибьютор продуктов питания для торговых сетей и HoReCa в Уральском регионе.",
        "product_lines": "сырная и мясная гастрономия, молочная продукция, масложировая группа",
        "moq": "от 2000 ₽",
        "price_note": None,
        "certificates": None,
        "delivery_terms": "регулярные партии, возможна дегустация",
        "notes": None,
        "source_url": "https://nash-souz.ru/about/",
    },
]


def _insert(repo: SupplierRepository, item: dict, created_via: str, status: str) -> None:
    item = dict(item)
    source_url = item.pop("source_url", None)
    data = SupplierCreate(**item)
    supplier = repo.create(data, created_via=created_via, source_url=source_url, status=status)
    try:
        vector_store.upsert_supplier_vector(supplier.id, embed_passage(supplier_embedding_text(data)))
        chunks = supplier_embedding_chunks(data)
        if chunks:
            vector_store.upsert_supplier_chunk_vectors(supplier.id, embed_passages(chunks))
    except Exception:
        pass


def seed_if_empty() -> None:
    db = SessionLocal()
    try:
        repo = SupplierRepository(db)
        if repo.count() > 0:
            return
        for item in DEMO_SUPPLIERS:
            _insert(repo, item, created_via="manual", status="demo")
        for item in REAL_SUPPLIERS:
            _insert(repo, item, created_via="ai_scrape", status="found")
    finally:
        db.close()
